/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.didi.example.dto;

import lombok.Builder;
import lombok.Data;

import java.util.Date;

/**
 * @author huangjin
 */
@Builder
@Data
public class UserDto {
  private Long userId;
  private String name;
  private String mobile;
  private Date createTime;
  private Date updateTime;
  private Boolean isDeleted;
}

